language: java
sudo: false
install: true

addons:
  apt:
    packages:
    - docker-ce
  sonarcloud:
    organization: benjaminvega-github
    token:
      secure: ZnY/Ixrmds06o4d7nwrDR55pCqluGIcPFwPabF2AdPw1MEOkkAXHSw0FMk3wHzrJSZr6iEyhMfINCpbeC3sJl6jy1xOSsgnol7VOGKogG9+Dsw3K319XF43hAH8LyyfMshIMVDjy2cKd74l7cY5CuP6KbtpxITnrC5YCLY933WN94hAdNmchUrwGp1ttOJHkQX9aBLU+yAjETUJQwgEgIWBKE6rbt8XlppWn0bkn/AzjCZYfG/zo16YIVWmvSREPdIJS6T0VdiQ/zte3Vo7wfbe1nJHM/+yd98X/mySrt+YdQ8j1M83Qb/TcgZi7mkyDnRkG9rICbZ3YjHDClw2O68y1ZcyzwDEUaIwbkZlhbpNrxT4i+UQvft7BQFlV8zCNS5bw2U2+KJgbqGaQtGS2t3AqE1wCoLGI/gSitxi+UCQKuVGa9dRHZqeHzIcVtWXpzMTqqibFNK6ZAIyHOyYdn11aZzamBxnDZQVclpqlm5jwPMS7PqXaLRkyPf/nHmZB36Y3x0gEzxU92A8ozR4KAHaHpnr6K2RsjcS1xnhbJwyPCH/IkGUDfDFK2mP6PogtH/AEkP02RZa2U4AJohzQ+vTKx/IFmHxm1yZ7t8g+OndrpMbGat72KBCJNZSPY48j28w1AgdfTqrgwFUat0phYr1Dyo4nqHZhO1HIReQawPI=
script:
- mvn clean install
- sonar-scanner

jdk:
- oraclejdk8
