# Use postgres/example user/password credentials
version: '2'

services:

  db:
    image: postgres
    ports:
    - 8432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: benjaminvegadelpino
      POSTGRES_USER: benjaminvegadelpino
      POSTGRES_DB: crm
